# TODO: add codecov.yml when we're ready to use it.
#ignore:
#  - "tomb"
#  - "tomb-lib/bench"
#  - "tomb-lib/test"
#
#comment:
#  layout: "reach, diff, flags, files"
#  require_changes: true
#
#github_checks:
#  annotations: false
#
#coverage:
#  status:
#    project:
#      default:
#        threshold: 5%
