[package]
name = "tomb-wasm"

# These are locked across the repository for now
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
async-trait = "0.1.68"
tomb-common = { path = "../tomb-common", version = "1.1.0" }
wasm-streams = "0.3.0"
wnfs.workspace = true
wnfs-wasm = "0.1.20"
web-sys = { version = "0.3.63", features = ["FormData", "HtmlFormElement"] }
reqwest = "0.11.18"
wasm-bindgen-futures = "0.4.36"
wnfs-common = "0.1.20"
rand.workspace = true
chrono.workspace = true
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.86"
serde_json.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.36"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
