[package]
name = "tomb-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3.54"
worker = "0.0.16"
tomb-common = { path = "../tomb-common" }
wasm-streams = "0.3.0"
wnfs.workspace = true
wnfs-wasm = { path = "../../rs-wnfs/wnfs-wasm" }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"