[package]
name = "tomb-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde.workspace = true
async-trait = "0.1.68"
tomb-common = { path = "../tomb-common" }
wasm-bindgen = "0.2.86"
wasm-streams = "0.3.0"
wnfs = { git = "https://github.com/wnfs-wg/rs-wnfs", features = ["wasm"] }
wnfs-wasm = "0.1.20"
web-sys = { version = "0.3.63", features = ["FormData", "HtmlFormElement"] }
reqwest = "0.11.18"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
