[package]
name = "tomb-wasm"
edition = { workspace = true}
version = { workspace = true}
repository = { workspace = true}
license = { workspace = true}

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wee_alloc"]
in_browser = []

[profile.release]
opt-level = "s" # Optimize for binary size

[dependencies]
# Workspace dependencies
anyhow = { workspace = true }
serde = { workspace = true }
wnfs = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
# Crate dependencies
async-trait = "0.1.68"
console_error_panic_hook = { version = "0.1.7", optional = true }
serde-wasm-bindgen = "0.5.0"
tomb-common = { path = "../tomb-common", version = "1.1.0" }
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = [
    "console",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "ReadableStream",
    "Window",
    "Crypto",
    "CryptoKey",
    "CryptoKeyPair",
    "AesKeyGenParams",
    "AesGcmParams",
    "RsaOaepParams",
    "SubtleCrypto",
]}
wee_alloc = { version = "0.4.5", optional = true }
wnfs-wasm = "0.1.20"
wnfs-common = "0.1.20"
wasm-bindgen = "0.2.86"
js-sys = "0.3.64"
futures-util = "0.3.28"
noosphere-car = "0.2.0"
futures = "0.3.28"
tokio-util = { version = "0.7.8", features = ["compat"] }
gloo = { version = "0.8.1", features = ["net"] }
rc = "0.1.1"
wasm-streams = "0.3.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.36"
