[package]
name = "tomb-crypt"
license = "LicenseRef-LICENSE.txt"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "^0.21"
openssl = { version = "^0.10", features = ["v110"] }
openssl-hkdf = "^0.2"
