[package]
name = "tomb-common"

# These are locked across the repository for now
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
wnfs.workspace = true
anyhow.workspace = true
async-trait = "0.1.68"
serde_json.workspace = true
reqwest = { version = "0.11.18", features = ["blocking", "multipart", "json"] }
rand.workspace = true
wasm-bindgen = "0.2.86"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
