[package]
name = "tomb-common"

# These are locked across the repository for now
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wnfs.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait = "0.1.68"
anyhow.workspace = true
reqwest = { version = "0.11.18", features = ["blocking", "multipart", "json"] }
unsigned-varint = "0.7.1"
rand.workspace = true
thiserror = "1.0.40"
hex = "0.4.3"
chrono.workspace = true

[dev-dependencies]
fs_extra.workspace = true
tokio.workspace = true
serial_test = "2.0.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
