[package]
name = "tomb-common"

# These are locked across the repository for now
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
wnfs = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1.68"
serde_json = { workspace = true }
reqwest = { version = "0.11.18", features = ["blocking", "multipart", "json"] }
rand = { workspace = true }
wasm-bindgen = "0.2.86"
thiserror = "1.0.40"
rsa = "0.9.2"
sha2 = "0.10.7"
spki = { version = "0.7.2", features = ["fingerprint", "alloc", "base64"] }

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dev-dependencies]
async-std = { version = "1.11", features = ["attributes"] }
base64 = "0.21.2"
hex-literal = "0.4.1"
