[package]
name = "tomb"
description = "Where shared types and functions should live for the tomb project"

# These are locked across the repository for now
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tomb-common = { path = "../tomb-common", version = "1.1.0" }
anyhow.workspace = true
jwalk.workspace = true
serde.workspace = true

# Dev-Dependencies: These should live under a different tag
chrono.workspace = true
clap.workspace = true
criterion.workspace = true
dir-assert.workspace = true
fake-file.workspace = true
fclones.workspace = true
fs_extra.workspace = true
lazy_static.workspace = true
rand.workspace = true
tokio.workspace = true
wnfs.workspace = true
zstd.workspace = true

assert_cmd = "2.0.11"
async-recursion = "1.0.4"
env_logger = "0.10.0"
indicatif = { version = "0.17.3", features = ["improved_unicode"] }
log = "0.4.17"
serial_test = "2.0.0"

# Benchmark for packing -> unpacking an input directory
[[bench]]
name = "pipeline"
harness = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
