name: 🔍 Continuous Integration
on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --examples

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets --all-features --tests -- -D warnings

  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: native tests
        run: RUST_BACKTRACE=1 cargo test --all-features
      - name: wasm tests
        working-directory: ./tomb-wasm
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        run: RUST_BACKTRACE=1 wasm-pack test --headless --firefox
      - name: doc tests
        run: RUST_BACKTRACE=1 cargo test --all-features --doc