name: Lint Commit Messages
on:
  - pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        continue-on-error: true
      - name: Add annotation on failure
        run: echo "::warning::CommitLint checks failed"
        if: failure()
