name: 🐳 Docker

on:
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  empty_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Nothing to do here."
# TODO: Implement docker builds in github actions
#  build-docker:
#    runs-on: ubuntu-latest
#    if: ${{ github.event_name == 'pull_request' }}
#
#    env:
#      DOCKER_BUILDKIT: 1
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      # https://github.com/docker/setup-qemu-action
#      - name: Setup QEMU
#        uses: docker/setup-qemu-action@v2
#
#      # https://github.com/docker/setup-buildx-action
#      - name: Setup Buildx
#        uses: docker/setup-buildx-action@v2
#        with:
#          buildkitd-flags: "--debug"
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Docker Build
#        uses: docker/build-push-action@v4
#        with:
#          build-args: |
#            RUST_BUILD_IMG=rust:1.65-slim-bullseye
#            DEBIAN_TAG=bullseye-slim
#          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dataprep:latest
#          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dataprep:latest,mode=max
#          context: .
#          # We don't add `linux/arm64` here, as it can cause GitHub runners to
#          # stall for too long.
#          platforms: linux/amd64
#
#          push: false
#          tags: |
#            ${{ github.repository_owner }}/dataprep:latest
